name: Scala/C++ CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:

  unit-tests:
    runs-on: ubuntu-slim

    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M

    steps:
      - uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1

      - name: build
        run: sbt compile

      - name: run tests
        run: sbt test
